CREATE TABLE `T_SAMPLE_TEST_TABLE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `STRING_COL` VARCHAR(45) NULL,
  `TIMESTAMP_COL` TIMESTAMP NULL,
  `NUMBER_COL` BIGINT NULL,
  `BOOL_COL` TINYINT NULL,
  PRIMARY KEY (`ID`));
